version: "3.8"

services:
  migrate:
    image: openfga/openfga:latest
    container_name: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@54.175.46.253:5432/openfga_db?sslmode=require
    command: migrate
    networks:
      - hodor-network

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga-container
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@54.175.46.253:5432/openfga_db?sslmode=require
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100
      - OPENFGA_HTTP_CORS_ALLOW_ORIGINS=*
      - OPENFGA_LOG_LEVEL=error
    networks:
      - hodor-network
    ports:
      - "8080:8080" #http
      - "3000:3000" #playground
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=127.0.0.1:8081"]
      interval: 3s
      timeout: 30s
      retries: 3

  openfga-import:
    depends_on:
      openfga:
        condition: service_healthy
    image: openfga/cli:v0.5.1
    container_name: openfga-import
    restart: "no"
    command: "store create --name anees-labs --api-url http://openfga:8080 --model /tmp/model.dsl"
    networks:
      - hodor-network
    volumes:
      - $PWD/openfga:/tmp

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kc-container
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://54.175.46.253:5432/keycloak?sslmode=require
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_URL: http://keycloak:8081
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: none
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./themes:/opt/keycloak/themes
      # - ./certs:/opt/keycloak/certs
      - ./providers:/opt/keycloak/providers
    ports:
      - "8081:8081"
    networks:
      - hodor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 20s
      timeout: 5s
      retries: 5
    command: /opt/keycloak/bin/kc.sh start-dev --http-port=8081 --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --spi-required-action-VERIFY_EMAIL_CODE-code-length=6 --spi-required-action-VERIFY_EMAIL_CODE-code-symbols=0123456789

networks:
  hodor-network:
    driver: bridge
